kind: Template
apiVersion: v1
metadata:
  name: f8forker
  creationTimestamp: null
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: f8forker
    creationTimestamp: null
    generation: 1
    labels:
      app: f8forker
  spec:
    triggers:
      - type: ConfigChange
    replicas: 1
    test: false
    selector:
      app: f8forker
      deploymentconfig: f8forker
    strategy:
      resources:
        limits:
          cpu: 2000m
          memory: 500Mi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: f8forker
          deploymentconfig: f8forker
      spec:
        containers:
          -
            name: f8forker
            image: 'registry.devshift.net/fabric8io/fabric8-forker:${IMAGE_TAG}'
            ports:
              - containerPort: 8080
                protocol: TCP
            resources: {  }
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: Always
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /status
                port: 8080
                scheme: HTTP
              failureThreshold: 3
              initialDelaySeconds: 15
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            livenessProbe:
              httpGet:
                path: /status
                port: 8080
                scheme: HTTP
              failureThreshold: 3
              initialDelaySeconds: 15
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {  }
  status: {}
- kind: Service
  apiVersion: v1
  metadata:
    name: f8forker
    creationTimestamp: null
    labels:
      app: f8forker
  spec:
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: f8forker
      deploymentconfig: f8forker
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {  }
parameters:
- name: IMAGE_TAG
  value: latest